package me.morishima.udlede.api.utils;

import me.morishima.udlede.Udlede;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.HashMap;
import java.util.Objects;
import java.util.TreeMap;

public class MinecraftLangSerializer {
    private static final String N = System.lineSeparator();
    private final TreeMap<String, HashMap<String, String>> maps = new TreeMap<>();

    public MinecraftLangSerializer() {}

    public void addUnNameMap(HashMap<String, String> map) {
        addNamedMap("!", map);
    }

    public void addNamedMap(String areaName, HashMap<String, String> map) {
        maps.put(areaName, map);
    }


    public String toString() {
        StringBuilder builder = new StringBuilder();

        builder.append("# This lang file is generated by Udlede.").append(N);

        maps.forEach((areaName, map) -> {
            if (!Objects.equals(areaName, "!")) builder.append("#").append(areaName).append(N);
            else builder.append(N);

            map.forEach((key, value) -> builder.append(String.format("%s=%s", key, value)).append(N));
            builder.append(N).append(N);
        });

        return builder.toString();
    }

    public void writeToFile(String path) {
        try (FileOutputStream fos = new FileOutputStream(path)) {
                var osw = new OutputStreamWriter(fos);
                osw.write(toString());
                osw.flush();
        } catch (IOException e) {
                Udlede.logger.error(e);
        }
    }

}
