package me.morishima.udlede.api.utils;

import me.morishima.udlede.Udlede;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Objects;
import java.util.TreeMap;

public class MinecraftLangSerializer {
    private static final String N = System.lineSeparator();
    private final TreeMap<String, TreeMap<String, String>> maps = new TreeMap<>();

    public MinecraftLangSerializer() {}

    public void addUnNameMap(TreeMap<String, String> map) {
        maps.put("!", map);
    }

    public void addNamedMap(String areaName, TreeMap<String, String> map) {
        maps.put(areaName, map);
    }


    public String toString() {
        StringBuilder builder = new StringBuilder();

        builder.append("# This lang file is generated by Udlede.").append(N);

        maps.forEach((areaName, map) -> {
            if (!Objects.equals(areaName, "!")) builder.append("#").append(areaName).append(N);
            else builder.append(N);

            map.forEach((key, value) -> builder.append(String.format("%s=%s", key, value)).append(N));
            builder.append(N).append(N);
        });

        return builder.toString();
    }

    public void writeToFile(String path) {
        try {
            Files.write(Paths.get(path), toString().getBytes());
        } catch (IOException e) {
            Udlede.logger.error("MinecraftLangSerializer: Caught IOException " + e);
            Udlede.logger.error("MinecraftLangSerializer: Cant write to file!");
        }
    }

}
